# Generated by Django 5.2.7 on 2025-10-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed', models.TextField(blank=True, help_text='Embed code from Google Maps')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('history', 'History'), ('organization', 'Organization Structure'), ('department', 'Department'), ('sport_gym', 'Sport & Gym'), ('recreation', 'Recreation'), ('classes_accommodation', 'Classes & Accommodation'), ('range', 'Range'), ('library', 'Library'), ('driving_school', 'Driving School'), ('dispensary', 'Dispensary'), ('course', 'Course'), ('admission_requirements', 'Admission Requirements'), ('fee_structure', 'Fee Structure'), ('application_process', 'Application Process'), ('home', 'Home')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
