# Generated by Django 5.2.7 on 2025-10-20 14:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('history', 'History'), ('organization', 'Organization Structure'), ('department', 'Department'), ('sport_gym', 'Sport & Gym'), ('recreation', 'Recreation'), ('classes_accommodation', 'Classes & Accommodation'), ('range', 'Range'), ('library', 'Library'), ('driving_school', 'Driving School'), ('dispensary', 'Dispensary'), ('course', 'Course'), ('admission_requirements', 'Admission Requirements'), ('fee_structure', 'Fee Structure'), ('application_process', 'Application Process')], max_length=50, unique=True),
        ),
    ]
