# Generated by Django 4.2.11 on 2026-02-01 15:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_post_author_post_excerpt_post_updated_at_post_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
